### ISSUE TITLE
Any Detail about the Checksum parameters on BC32

### ISSUE THREAD

**Issue by aaronisme** [BlockchainCommons/Research#11]
On the paper [BC32](https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-0004-bc32.md), there is a Todo on  Checksum parameters, any detail info about it? what the parameters are currently using? 

and I have check out the code on https://github.com/BlockchainCommons/bc-bech32/blob/master/src/segwit_addr.c

use version_bech32_bis(0x3fffffff) XOR with checksum, is it just for seperating with the origin bech32 ?

**Comment by stepansnigirev** [comment]
+1, it would be interesting to know what is the motivation for a different constant.
It would be convenient to just use `bech32_encode(hrp, data)` with an empty string as hrp and no leading `1`...

**Comment by wolfmcnally** [comment]
As we're no longer supporting BC32 (having been superseded by ByteWords/UR) I'm closing this.
