### ISSUE TITLE
Test Vector on bc-bech32

### ISSUE THREAD

**Issue by aaronisme** [BlockchainCommons/Research#12]
Hi, I think the second test vector on https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-0004-bc32.md probably not correct. 

should be 'my6qv05zqq0wcpv9aeq6khvwfdcr5jlp7uawcg0pgwgjc4shjm6xu' after encoded?

I have tested using the test case for https://github.com/BlockchainCommons/bc-bech32

**Comment by wolfmcnally** [comment]
PR #13 issued for fix.
