### ISSUE TITLE
Version bits for SSKR?

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Research#22]
In https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-011-sskr.md, should we have a version bit or bytes for SSKR so that we are not 100% intersecting the binary version of SLIP-39? Not that they are exposing that anywhere. Is the customization string of`shamir` enough? I was always a bit uncomfortable with that trick in case we ever wanted to upgrade the checksum mechanism (say to bc32).

I know that @ksedgwic would ideally whatever we do to be small enough that when converted to mnemonics can fit on 2 of his metal doglegs. 15 characters per line, 6 lines per tag. So if a 1 byte version byte puts us over in whatever final mnemonic scheme we come up with, it could hurt. So it could maybe be a nibble somewhere?

-- Christopher Allen

**Comment by wolfmcnally** [comment]
We're not really intersecting the binary version of SLIP-39, you can't feed the CBOR into the SLIP-39 algorithm meaningfully unless you translate all the fields.

**Comment by wolfmcnally** [comment]
We *do* have a reserved field of four bits in the SSKR share 5-byte header that is currently required to be all zeros. This can serve as a version number if we need to enhance our own header in the future, but still has no bearing on the compatibility with SLIP-39, because there never was any.
