### ISSUE TITLE
Bytewords (BCR-2020-012) checksum

### ISSUE THREAD

**Issue by wolfmcnally** [BlockchainCommons/Research#23]
The choice to use the first four bytes of a CRC32 hash of a Bytewords body is open for comment. This issue is being tracked here. Please leave your comments below.

**Comment by ChristopherA** [comment]
My argument about using CRC32 vs a truncated hash is that the goal is error-detection, and for the same size of messages and CRC, there are proofs that it will detect more kinds of errors than a truncated hash function, which at best is 1/2 of its size, and a truncated hash is not provable. Hashes, in particular with HMAC constructions, have a different purpose than just error-detection, as they are used with encrypted data. Our data is not encrypted, so I believe it is a mistake for instance to use a truncated SHA-256.

However, as I'm not as expert on various CRC choices, thus we are open to input.

**Comment by wolfmcnally** [comment]
This has been open for over 8 months with no further comment, so I'm closing it.
