### ISSUE TITLE
bcr-2020-005-ur: sha256 digest

### ISSUE THREAD

**Issue by stepansnigirev** [BlockchainCommons/Research#26]
sha256 digest of the message is 32 bytes, when converted to bc2 it is 58 characters long.
If I understand correctly it is only used to check the integrity of all pieces.

I have two suggestions:
- take only a part of the digest, for example 8 bytes instead of all 32, it is good enough for the checksum, and error correction is not possible with hash digests anyways
- allow transmitting hash digest only in one QR code, not in all of them - I don't see a reason to waste QR code capacity and transmit the same data in all frames.  Or make it optional for sequential QR codes as well and let the implementation decide if they want to use it or not.

**Comment by ChristopherA** [comment]
I think for a variety of reasons we are moving to CRC-32. Part of this is that though there are no known problems with partial sha256, CRC-32 is smaller, more broadly deployed, and does has provable error detection. The benefits of using a hash (which has different properties than a detection) are only available when you have the full hash, so we are moving in that direction. cc/ @wolfmcnally

**Comment by wolfmcnally** [comment]
Closing this due to it being mooted by move to UR 2.0 spec.
