### ISSUE TITLE
Rust implementation of UR

### ISSUE THREAD

**Issue by dspicher** [BlockchainCommons/Research#39]
Hi!

I'm interested in working on a Rust implementation of Uniform Resources, does anybody know if somebody has already started to do this?

**Comment by ChristopherA** [comment]
Several people have been talking about rust implementations of a number of the Blockchain Commons libraries, but I've not seen one yet.

A better place for this discussion would be https://github.com/BlockchainCommons/AirgappedSigning/discussions where we've been moving our Signal chat to (albeit slowly). You are welcome to be added to the Signal channel as well.

**Comment by dspicher** [comment]
c.f. https://github.com/BlockchainCommons/Airgapped-Wallet-Community/discussions/20
