### ISSUE TITLE
A new specification for bc32 or bc64 with no HRP/UIR collision?

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Research#4]
Re: https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-0003-uri-binary-compatibility.md

Should we define a new specification that is bech32 but addresses the HRP collision problem with the URI reserved character set? Maybe call it bc32?

I'm also trying to get the parameters from @sipa for a possible 64-128 byte optimized form that could also form a new specification. (see Twitter thread https://twitter.com/pwuille/status/1250663639930953729?s=20 )

I like bech32 for its ability to be read over phone and to offer both error detection and some error correction. But we have to specify it carefully, quoting @sipa in [BIP-0173](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki ):
>An unfortunate side effect of error correction is that it erodes error detection: correction changes invalid inputs into valid inputs, but if more than a few errors were made then the valid input may not be the correct input.…Because of this, implementations SHOULD NOT implement correction beyond potentially suggesting to the user where in the string an error might be found, without suggesting the correction to make.

This limitation also makes bech32 as an encoding format limited in another way that Base64URL format is not — it is only suitable for short lengths.

Either, or both of these new specifications I might be able to run the flag up to get standardized in IETF or W3C.

cc/ @maaku @kanzure @Fonta1n3 @ksedgwic

-- Christopher Allen

**Comment by wolfmcnally** [comment]
This has now been addressed with the implementation of BC32.
