### ISSUE TITLE
bytewords should follow alphabetically consistently

### ISSUE THREAD

**Issue by gorazdko** [BlockchainCommons/Research#45]
## Abstract

In `bcr-2020-012-bytewords.md` most of the words look to be ordered alphabetically. The exception I ran into is
the last line:

`0xf8: yoga yurt zaps zest zinc zone zoom zero`

The same issue is in both (c and c++) implementations of bytewords.

This causes lots of difficulties on the UI side in lethekit.

**Comment by wolfmcnally** [comment]
I also found a second alphabetization error in the word list. I will have a fix for this out shortly, but it will be a *breaking fix*.

**Comment by wolfmcnally** [comment]
Please see my commentary on the resolution of this issue [here](https://github.com/BlockchainCommons/Airgapped-Wallet-Community/discussions/19).
