### ISSUE TITLE
incorrect header for CBOR byte string in BCR-2020-005 paper

### ISSUE THREAD

**Issue by m0dB** [BlockchainCommons/Research#64]
Hi,

The BCR-2020-005 paper says (about CBOR byte strings)

"If the encoded byte string has 65536..2^32-1 bytes, it is preceded by (0x60, b1, b2, b3, b4) where b(n) is the big-endian four byte length of the following byte string."

This is not correct. According to https://tools.ietf.org/html/rfc7049 the header for 65536+ byte strings is 0x5a (Indeed, the value after 0x59. 0x60 is the header of shortest UTF-8 strings)

**Comment by wolfmcnally** [comment]
@m0dB Fixed! Thank you.
