### ISSUE TITLE
Why fountain codes and not Low-Density Parity-Check?

### ISSUE THREAD

**Issue by dcale** [BlockchainCommons/Research#70]
This is not really an issue just a question.

**Comment by ChristopherA** [comment]
There have been second hand reports of some patent issues. We decided to avoid them with one known not to have that issue.

**Comment by dcale** [comment]
ok, thanks for the clarification!

**Comment by dcale** [comment]
@ChristopherA  do we know how the two encoding methods compare in terms of efficiency?
