### ISSUE TITLE
incorrect test vectors: hdkey serialization

### ISSUE THREAD

**Issue by gorazdko** [BlockchainCommons/Research#83]
## Abstract

Across HD keys and output descriptors the test vectors are incomplete wrt *depth* and *child number*:

EDIT: removed incorrect example and showed a new example:

## Output Descriptors

* incorrect depth. In certain cases depth must be provided despite derivation-path presence:
```
04 ; version 4
88b21e ; `xpub`
04 ; depth 4
78412e3a ; parent fingerprint
fffffffe ; child number
637807030d55d01f9a0cb3a7839515d796bd07706386a6eddf06cc29a65a0e29 ; chain code
02d2b36900396c9282fa14628566582f206a5dd0bcc8d5e892611806cafb0301f0 ; key data
7e652001 ; base58 checksum

    In the CBOR diagnostic notation:

403( ; public-key-hash
	303({ ; crypto-hdkey
		3: h'02d2b36900396c9282fa14628566582f206a5dd0bcc8d5e892611806cafb0301f0', ; key-data
		4: h'637807030d55d01f9a0cb3a7839515d796bd07706386a6eddf06cc29a65a0e29', ; chain-code
		6: 304({ ; origin: crypto-keypath
			1: [ ; components
				44, true, 0, true, 0, true ; 44'/0'/0'
			],
			2: 3545084735 ; origin-fingerprint
		}),
```

## Crypto address

How to get version for the witness program? From type which is optional?

```
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Payload {
    /// P2PKH address
    PubkeyHash(PubkeyHash),
    /// P2SH address
    ScriptHash(ScriptHash),
    /// Segwit addresses
    WitnessProgram {
        /// The witness program version
        version: bech32::u5,
        /// The witness program
        program: Vec<u8>,
    },
}
```

**Comment by gorazdko** [comment]
This is what the problem seems to be: In xpub serialization there are certain fields (depth and child number) which are incorrectly assumed by the test vectors that they can be derived from the derivation path of the output descriptor.

**Comment by wolfmcnally** [comment]
Depth is not missing: it is an optional field in crypto-keypath:

![image](https://user-images.githubusercontent.com/676176/119565029-49f06980-bd5e-11eb-8514-e866edf5c24e.png)

https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-007-hdkey.md#cddl-for-key-path

**Comment by ChristopherA** [comment]
@gorazdko Is this closed yet?

**Comment by gorazdko** [comment]
No. I offered this to interns.

EDIT: assigned to @nochiel
